spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_admin?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: sulei1124

  data:
    redis:
      host: localhost
      port: 6379
      password: sulei1124

logging:
  level:
    root: INFO
    com.xiaoins.admin: DEBUG
    com.baomidou.mybatisplus: DEBUG

